### ISSUE TITLE
Twitter id's don't fit in a csv file!

### ISSUE THREAD

**Issue by fpcarva** [Minyall/gephi_twitter_media_downloader#11]
I'm trying to put a tweet id list but the csv format approximates the value and I lose the original id number. Is there any way to use a json or xlsx? How do you manage to put such large id's in an xlsx file? An example of a tweet ID that I tried to use '1294030472427835393'. When it is approximated in the csv the resulting value is '1294030472427830000'. Thank you very much !

**Comment by alexanderosmith** [comment]
Hey @fpcarva, this is a problem with Excel xlsx formats that my lab runs into all the time. The easiest solution is to append ID_ to the start of the tweet ID, and then convert it to a string. That way, Excel will read it as a string rather than a numeric field.

**Comment by fpcarva** [comment]
@alexanderosmith Cool!!! 
I thought about that. But how am I going to make it read only the part of the id itself? Honestly, I still don't understand how to use this repository, could you do a simulation of the steps I should take? Thank you really much

**Comment by alexanderosmith** [comment]
For issues such as this, I usually use a reg ex expression that only reads the numbers of the field. 

An alternative might be to never open your file in Excel. This might sound strange, but the conversion only happens when you open it in Excel or similar spreadsheet software. If the file stays as a csv, you could open the file in an plain rtf editor, a text editor, python, or R, and likely you'll see the numbers don't convert.

If you can manage either of those, one of them might solve your problem.

**Comment by alexanderosmith** [comment]
As for walking through the repository, I should probably leave that to the developer. I haven't tried to use this in a long while as I've begun working on something that has been integrated into a larger data collection project. I'm keeping this one in mind because parts of it might work to help in the development for my project.

**Comment by fpcarva** [comment]
Thank You @alexanderosmith . This solution help me and my team! 

> Para questões como essa, geralmente uso uma expressão reg ex que lê apenas os números do campo.
> 
> Uma alternativa pode ser nunca abrir o arquivo no Excel. Isso pode parecer estranho, mas a conversão só acontece quando você abre no Excel ou software de planilha semelhante. Se o arquivo permanecer como csv, você poderá abri-lo em um editor rtf simples, um editor de texto, python ou R e provavelmente verá que os números não são convertidos.
> 
> Se você puder gerenciar qualquer um deles, um deles pode resolver seu problema.

Thank You @alexanderosmith . This solution help me and my team!

**Comment by fpcarva** [comment]
> For issues such as this, I usually use a reg ex expression that only reads the numbers of the field.
> 
> An alternative might be to never open your file in Excel. This might sound strange, but the conversion only happens when you open it in Excel or similar spreadsheet software. If the file stays as a csv, you could open the file in an plain rtf editor, a text editor, python, or R, and likely you'll see the numbers don't convert.
> 
> If you can manage either of those, one of them might solve your problem.

Thank You @alexanderosmith . This solution help me and my team!
